name: Test control_msgs
on:
  pull_request:
  push:
    branches:
      - kinetic-devel
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    env:
      # Ensure downstream packages ros_controllers and control_toolbox still build
      # Do not run downstream tests, as building is sufficient and tests may be flakey
      UPSTREAM_WORKSPACE:   'https://raw.github.com/ros-controls/ros_control/$ROS_DISTRO-devel/ros_control.rosinstall -ros_controllers -control_toolbox -control_msgs'
      DOWNSTREAM_WORKSPACE: 'https://raw.github.com/ros-controls/ros_control/$ROS_DISTRO-devel/ros_control.rosinstall -ros_control -realtime_tools -control_msgs'
      NOT_TEST_DOWNSTREAM: true
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: main}
          - {ROS_DISTRO: kinetic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
    steps:
      - uses: actions/checkout@v1
      - uses: ros-industrial/industrial_ci@master
        env: ${{matrix.env}}
